---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(lubridate)
```
```{r}
activity <- read.csv("activity.csv")
str(activity)
summary(activity)
```
## What is mean total number of steps taken per day?
```{r }
total_steps_per_day <- activity %>%
group_by(date) %>%
summarize(total_steps = sum(steps, na.rm = TRUE))
head(total_steps_per_day)
```

## What is the average daily activity pattern?
```{r}
avg_steps_interval <- activity %>%
group_by(interval) %>%
summarize(mean_steps = mean(steps, na.rm = TRUE))
ggplot(avg_steps_interval, aes(x = interval, y = mean_steps)) +
geom_line(color = "blue") +
labs(title = "Average Steps per 5-minute Interval", x = "Interval", y = "Average Steps")
```

## Imputing missing values
```{r}
num_missing <- sum(is.na(activity$steps))
num_missing
activity_imputed <- activity %>%
group_by(interval) %>%
mutate(steps = ifelse(is.na(steps), mean(steps, na.rm = TRUE), steps)) %>%
ungroup()
```
```{r}
total_steps_per_day_imputed <- activity_imputed %>%
group_by(date) %>%
summarize(total_steps = sum(steps))
ggplot(total_steps_per_day_imputed, aes(x = total_steps)) +
geom_histogram(binwidth = 1000, fill = "orange", color = "black") +
labs(title = "Histogram of Total Steps per Day (Imputed)", x = "Total Steps per Day", y = "Frequency")
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity_imputed$day_type <- ifelse(weekdays(as.Date(activity_imputed$date)) %in% c("Saturday", "Sunday"), "weekend", "weekday")
avg_steps_day_type <- activity_imputed %>%
group_by(interval, day_type) %>%
summarize(mean_steps = mean(steps), .groups = "drop")
ggplot(avg_steps_day_type, aes(x = interval, y = mean_steps, color = day_type)) +
geom_line() +
facet_wrap(~day_type, ncol = 1) +
labs(title = "Average Steps per Interval: Weekday vs Weekend", x = "Interval", y = "Average Steps")
```
